server:
  port: 8761
spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false

---
# --spring.profiles.active=server1
server:
  port: 8761
spring:
  application:
    name: eureka
  profiles: server1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka,http://localhost:8763/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false

---
# --spring.profiles.active=server2
server:
  port: 8762
spring:
  application:
    name: eureka
  profiles: server2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8763/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false

---
# --spring.profiles.active=server2
server:
  port: 8763
spring:
  application:
    name: eureka
  profiles: server3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false
